name: Build

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["8", "11"]

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up latest Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java-version }}'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Install Blosc native library
        run: sudo apt-get install -y libblosc1

      - name: Run tests
        run: mvn -B test
